# Introduction to Pandas

Pandas is a package built on top of numpy which incorporates many additional features which make it more convenient for data analysis. One main addition is the inclusion of row and column labels, which make pandas function much like spreadsheet software. It also includes tools for much more complex computations than regular numpy allows

In [30]:
import pandas as pd
import numpy as np
# by default, pandas only shows the beginning and end of a large dataframe
# You can choose how many rows and columns to show.
# If you want to see all of the rows, set the respective value to None
pd.options.display.max_rows = 100 
pd.options.display.max_columns = 50

## Importing data
There are a lot of built-in functions for importing data to pandas, common examples include: 

- directly from files on local path or server 
- supported databases 
- web sources / directly from URL 

For a full list of the supported methods, see [the documentation on pandas](https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html).

In this example, we're going to load data formatted as a csv from a website URL. In particular, it is a direct link to a file hosted in our course github repository.

The data we're loading is a simplified pokedex which includes the number, name, base stats, types, abilities, and colors of each pokemon. We'll be using this data to explore the functionality of pandas. 

The primary class of pandas is the DataFrame, which functions like a spreadsheet (like in excel). It allows for named rows and columns. Data types between two different columns can vary, but entries within the same column should have the same type.

In [31]:
# URL for data hosted online
pokedex_url = 'https://raw.githubusercontent.com/bwsi-remote-sensing-2023/01-Intro-to-python/master/pokedex.csv' 
pokedex_df = pd.read_csv(pokedex_url, index_col='Index') # create a dataframe from a csv, set the column titled "Index" as the row labels

In [32]:
# in our case, the cloned repository includes the pokedex file in the folder, 
# so we could equivalently use the filename instead of a URL
pokedex_df = pd.read_csv('pokedex.csv', index_col='Index')

In [4]:
# We'll do some cleanup to deal with empty values
pokedex_df = pokedex_df.fillna('') # fill in the NaN values with empty string 
pokedex_df # prints out the dataframe

,Pokemon,HP,Atk,Def,SpAtk,SpDef,Speed,Total,Type I,Type II,Ability I,Ability II,Hidden Ability,Color
Index,,,,,,,,,,,,,,
1.0,Bulbasaur,45,49,49,65,65,45,318,Grass,Poison,Overgrow,,Chlorophyll,Green
2.0,Ivysaur,60,62,63,80,80,60,405,Grass,Poison,Overgrow,,Chlorophyll,Green
3.0,Venusaur,80,82,83,100,100,80,525,Grass,Poison,Overgrow,,Chlorophyll,Green
4.0,Charmander,39,52,43,60,50,65,309,Fire,,Blaze,,Solar Power,Red
5.0,Charmeleon,58,64,58,80,65,80,405,Fire,,Blaze,,Solar Power,Red
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
798.0,Kartana,59,181,131,59,31,109,570,Grass,Steel,Beast Boost,,,White
799.0,Guzzlord,223,101,53,97,53,43,570,Dark,Dragon,Beast Boost,,,Black
800.0,Necrozma,97,107,101,127,89,79,600,Psychic,,Prism Armor,,,Black
801.0,Magearna,80,95,115,130,115,65,600,Steel,Fairy,Soul-Heart,,,Gray
802.0,Marshadow,90,125,80,90,90,125,600,Fighting,Ghost,Technician,,,Gray

## Indexing
Like numpy, you can index a dataframe to select elements or subsets of entries. There are multiple ways to index in pandas, with two following methods recommended:

- `.loc[]` 
- `.iloc[]`

### .loc[ ] name-based indexing
The first way, using `.loc[a,b]` indexes based on the __values__ of the row index and column names. This allows us to get entries where the row index value equals `a` and the column name equals `b`.

In [5]:
# Get the entry for index value 745.1 - Lycanroc (midnight)
pokedex_df.loc[745.1]

Pokemon           Lycanroc (midnight)
HP                                 85
Atk                               115
Def                                75
SpAtk                              55
SpDef                              75
Speed                              82
Total                             487
Type I                           Rock
Type II
Ability I                    Keen Eye
Ability II              Vital Spirit
Hidden Ability               No Guard
Color                           Brown
Name: 745.1, dtype: object

In [6]:
# You can get specific column values for a single entry
pokedex_df.loc[250,['Pokemon','Type I','Type II']]

Pokemon    Swinub
Type I        Ice
Type II    Ground
Name: 250.0, dtype: object

In [7]:
# you can use the : notation to slice multiple rows and columns
pokedex_df.loc[690:700,'Pokemon':'Total']

          Pokemon   HP  Atk  Def  SpAtk  SpDef  Speed  Total
Index
690.0      Skrelp   50   60   60     60     60     30    320
691.0    Dragalge   65   75   90     97    123     44    494
692.0   Clauncher   50   53   62     58     63     44    330
693.0   Clawitzer   71   73   88    120     89     59    500
694.0  Helioptile   44   38   33     61     43     70    289
695.0   Heliolisk   62   55   52    109     94    109    481
696.0      Tyrunt   58   89   77     45     45     48    362
697.0   Tyrantrum   82  121  119     69     59     71    521
698.0      Amaura   77   59   50     67     63     46    362
699.0     Aurorus  123   77   72     99     92     58    521
700.0     Sylveon   95   65   65    110    130     60    525

In [8]:
# Similarly to numpy, you can use the : notation without indices on a side to mean "from beginning" or "to end"
pokedex_df.loc[:10,"Ability I":]

         Ability I Ability II Hidden Ability  Color
Index
1.0       Overgrow               Chlorophyll  Green
2.0       Overgrow               Chlorophyll  Green
3.0       Overgrow               Chlorophyll  Green
4.0          Blaze               Solar Power    Red
5.0          Blaze               Solar Power    Red
6.0          Blaze               Solar Power    Red
7.0        Torrent                 Rain Dish   Blue
8.0        Torrent                 Rain Dish   Blue
9.0        Torrent                 Rain Dish   Blue
10.0   Shield Dust                  Run Away  Green

In [9]:
# and : by itself gives all of the entries in that dimension
pokedex_df.loc[:,'Pokemon'].head(10) #just return top 10 entries

Index
1.0      Bulbasaur
2.0        Ivysaur
3.0       Venusaur
4.0     Charmander
5.0     Charmeleon
6.0      Charizard
7.0       Squirtle
8.0      Wartortle
9.0      Blastoise
10.0      Caterpie
Name: Pokemon, dtype: object

### .iloc[ ] integer indexing

The second way, using `.iloc[i,j]` uses the numpy-style integer indices to get a value. In this case, iloc takes integer values from 0 to the number of entries in that dimension. 

Like numpy, `.iloc[i,j]` gives the entry at the $i^{th}$ row and $j^{th}$ column.

In [10]:
pokedex_df.iloc[100] # gets 101st row (recall python counts from 0)

Pokemon            Electrode
HP                        60
Atk                       50
Def                       70
SpAtk                     80
SpDef                     80
Speed                    140
Total                    480
Type I              Electric
Type II
Ability I         Soundproof
Ability II            Static
Hidden Ability     Aftermath
Color                    Red
Name: 110.0, dtype: object

In [11]:
# The : style indexing also works for iloc
pokedex_df.iloc[25:30, 0:8]

         Pokemon  HP  Atk  Def  SpAtk  SpDef  Speed  Total
Index
27.0      Raichu  60   90   55     90     80    100    475
28.0   Sandshrew  50   75   85     20     30     40    300
29.0   Sandslash  75  100  110     45     55     65    450
30.0    Nidoran♀  55   47   52     40     40     41    275
31.0    Nidorina  70   62   67     55     55     56    365

## Changing index column
You can change the index column of the dataframe with `.set_index()` or reset it to default numerical indexing with `.reset_index()`.

Note however, that these operations create a __copy__ of the original dataframe, and do not change the dataframe "in place" (i.e. doesn't change the original object)

In [12]:
# reset index to be default numerical index
reindexed_pokedex = pokedex_df.reset_index()
reindexed_pokedex.head()

,Index,Pokemon,HP,Atk,Def,SpAtk,SpDef,Speed,Total,Type I,Type II,Ability I,Ability II,Hidden Ability,Color
0,1.0,Bulbasaur,45,49,49,65,65,45,318,Grass,Poison,Overgrow,,Chlorophyll,Green
1,2.0,Ivysaur,60,62,63,80,80,60,405,Grass,Poison,Overgrow,,Chlorophyll,Green
2,3.0,Venusaur,80,82,83,100,100,80,525,Grass,Poison,Overgrow,,Chlorophyll,Green
3,4.0,Charmander,39,52,43,60,50,65,309,Fire,,Blaze,,Solar Power,Red
4,5.0,Charmeleon,58,64,58,80,65,80,405,Fire,,Blaze,,Solar Power,Red

In [13]:
# Change the index to the Pokemon name column
pokedex_indexed_by_name = pokedex_df.reset_index().set_index('Pokemon')
pokedex_indexed_by_name

,Index,HP,Atk,Def,SpAtk,SpDef,Speed,Total,Type I,Type II,Ability I,Ability II,Hidden Ability,Color
Pokemon,,,,,,,,,,,,,,
Bulbasaur,1.0,45,49,49,65,65,45,318,Grass,Poison,Overgrow,,Chlorophyll,Green
Ivysaur,2.0,60,62,63,80,80,60,405,Grass,Poison,Overgrow,,Chlorophyll,Green
Venusaur,3.0,80,82,83,100,100,80,525,Grass,Poison,Overgrow,,Chlorophyll,Green
Charmander,4.0,39,52,43,60,50,65,309,Fire,,Blaze,,Solar Power,Red
Charmeleon,5.0,58,64,58,80,65,80,405,Fire,,Blaze,,Solar Power,Red
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Kartana,798.0,59,181,131,59,31,109,570,Grass,Steel,Beast Boost,,,White
Guzzlord,799.0,223,101,53,97,53,43,570,Dark,Dragon,Beast Boost,,,Black
Necrozma,800.0,97,107,101,127,89,79,600,Psychic,,Prism Armor,,,Black
Magearna,801.0,80,95,115,130,115,65,600,Steel,Fairy,Soul-Heart,,,Gray
Marshadow,802.0,90,125,80,90,90,125,600,Fighting,Ghost,Technician,,,Gray

In [14]:
# note that the original dataframe was not affected
pokedex_df

,Pokemon,HP,Atk,Def,SpAtk,SpDef,Speed,Total,Type I,Type II,Ability I,Ability II,Hidden Ability,Color
Index,,,,,,,,,,,,,,
1.0,Bulbasaur,45,49,49,65,65,45,318,Grass,Poison,Overgrow,,Chlorophyll,Green
2.0,Ivysaur,60,62,63,80,80,60,405,Grass,Poison,Overgrow,,Chlorophyll,Green
3.0,Venusaur,80,82,83,100,100,80,525,Grass,Poison,Overgrow,,Chlorophyll,Green
4.0,Charmander,39,52,43,60,50,65,309,Fire,,Blaze,,Solar Power,Red
5.0,Charmeleon,58,64,58,80,65,80,405,Fire,,Blaze,,Solar Power,Red
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
798.0,Kartana,59,181,131,59,31,109,570,Grass,Steel,Beast Boost,,,White
799.0,Guzzlord,223,101,53,97,53,43,570,Dark,Dragon,Beast Boost,,,Black
800.0,Necrozma,97,107,101,127,89,79,600,Psychic,,Prism Armor,,,Black
801.0,Magearna,80,95,115,130,115,65,600,Steel,Fairy,Soul-Heart,,,Gray
802.0,Marshadow,90,125,80,90,90,125,600,Fighting,Ghost,Technician,,,Gray

## Logical indexing
In data analysis we can apply boolean logic refering to testing for 'True' or 'False' (1/0 in binary). Known as logical indexing we can use conditionals on a column, for example, testing if the value of the column is greater than a value. What's returned is a boolean column of the same size, with a value of `True` wherever it is true, and `False` otherwise. (This can similarly be done in numpy).

In [15]:
pokedex_df['Total'] > 520

Index
1.0      False
2.0      False
3.0       True
4.0      False
5.0      False
         ...
798.0     True
799.0     True
800.0     True
801.0     True
802.0     True
Name: Total, Length: 820, dtype: bool

If you take that boolean column and use it to index the dataframe, you can get all of the entries that satisfy that condition.

In [16]:
pokedex_df.loc[pokedex_df['Total']>=520] # all of the pokemon with total base stats greater than 500

,Pokemon,HP,Atk,Def,SpAtk,SpDef,Speed,Total,Type I,Type II,Ability I,Ability II,Hidden Ability,Color
Index,,,,,,,,,,,,,,
3.0,Venusaur,80,82,83,100,100,80,525,Grass,Poison,Overgrow,,Chlorophyll,Green
6.0,Charizard,78,84,78,109,85,100,534,Fire,Flying,Blaze,,Solar Power,Red
9.0,Blastoise,79,83,100,85,105,78,530,Water,,Torrent,,Rain Dish,Blue
64.0,Arcanine,90,110,80,100,80,95,555,Fire,,Intimidate,Flash Fire,Justified,Brown
99.0,Cloyster,50,90,180,85,45,70,520,Water,Ice,Shell Armor,Skill Link,Overcoat,Purple
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
798.0,Kartana,59,181,131,59,31,109,570,Grass,Steel,Beast Boost,,,White
799.0,Guzzlord,223,101,53,97,53,43,570,Dark,Dragon,Beast Boost,,,Black
800.0,Necrozma,97,107,101,127,89,79,600,Psychic,,Prism Armor,,,Black
801.0,Magearna,80,95,115,130,115,65,600,Steel,Fairy,Soul-Heart,,,Gray
802.0,Marshadow,90,125,80,90,90,125,600,Fighting,Ghost,Technician,,,Gray

In [17]:
# Get all of the pokemon of a given color
pokedex_df.loc[pokedex_df['Color']=='Black']

,Pokemon,HP,Atk,Def,SpAtk,SpDef,Speed,Total,Type I,Type II,Ability I,Ability II,Hidden Ability,Color
Index,,,,,,,,,,,,,,
174.0,Snorlax,160,110,65,65,110,30,540,Normal,,Immunity,Thick Fat,Gluttony,Black
162.0,Umbreon,95,65,110,60,130,65,525,Dark,,Synchronize,,Inner Focus,Black
226.0,Murkrow,60,85,42,85,42,91,405,Dark,Flying,Insomnia,Super Luck,Prankster,Black
230.0,Unown,48,72,48,72,48,48,336,Psychic,,Levitate,,,Black
244.0,Sneasel,55,95,55,35,75,115,430,Dark,Ice,Inner Focus,Keen Eye,Pickpocket,Black
260.0,Houndour,45,60,30,80,50,65,330,Dark,Fire,Early Bird,Flash Fire,Unnerve,Black
261.0,Houndoom,75,90,50,110,80,95,500,Dark,Fire,Early Bird,Flash Fire,Unnerve,Black
328.0,Mawile,50,85,85,55,55,50,380,Steel,Fairy,Hyper Cutter,Intimidate,Sheer Force,Black
352.0,Spoink,60,25,35,70,80,60,330,Psychic,,Thick Fat,Own Tempo,Gluttony,Black
363.0,Seviper,73,100,60,100,60,65,458,Poison,,Shed Skin,,Infiltrator,Black
371.0,Claydol,60,70,105,70,120,75,500,Ground,Psychic,Levitate,,,Black
380.0,Shuppet,44,75,35,63,33,45,295,Ghost,,Insomnia,Frisk,Cursed Body,Black
381.0,Banette,64,115,65,83,63,65,455,Ghost,,Insomnia,Frisk,Cursed Body,Black
382.0,Duskull,20,40,90,30,90,25,295,Ghost,,Levitate,,,Black
383.0,Dusclops,40,70,130,60,130,25,455,Ghost,,Pressure,,,Black
227.0,Honchkrow,100,125,52,105,52,71,505,Dark,Flying,Insomnia,Super Luck,Moxie,Black
461.0,Chatot,76,65,45,92,42,91,411,Normal,Flying,Keen Eye,Tangled Feet,Big Pecks,Black
173.0,Munchlax,135,85,40,40,85,5,390,Normal,,Pickup,Thick Fat,Gluttony,Black
245.0,Weavile,70,120,65,45,85,125,510,Dark,Ice,Pressure,,Pickpocket,Black
384.0,Dusknoir,45,100,135,65,135,45,525,Ghost,,Pressure,,,Black
487.0,Giratina,150,100,120,100,120,90,680,Ghost,Dragon,Pressure,,Telepathy,Black
487.1,Giratina (O),150,120,100,120,100,90,680,Ghost,Dragon,Levitate,,,Black
491.0,Darkrai,70,90,90,135,90,125,600,Dark,,Bad Dreams,,,Black
522.0,Blitzle,45,60,32,50,32,76,295,Electric,,Lightningrod,Motor Drive,Sap Sipper,Black
523.0,Zebstrika,75,100,63,80,63,116,497,Electric,,Lightningrod,Motor Drive,Sap Sipper,Black
561.0,Sigilyph,72,58,80,103,80,97,490,Psychic,Flying,Wonder Skin,Magic Guard,Tinted Lens,Black
562.0,Yamask,38,30,85,55,65,30,303,Ghost,,Mummy,,,Black
608.0,Lampent,60,40,60,95,60,55,370,Ghost,Fire,Flash Fire,Flame Body,Shadow Tag,Black
609.0,Chandelure,60,55,90,145,90,80,520,Ghost,Fire,Flash Fire,Flame Body,Shadow Tag,Black
644.0,Zekrom,100,150,120,120,100,90,680,Dragon,Electric,Teravolt,,,Black
664.0,Scatterbug,38,35,40,27,25,35,200,Bug,,Shield Dust,Compound Eyes,Friend Guard,Black
665.0,Spewpa,45,22,60,27,30,29,213,Bug,,Shed Skin,,Friend Guard,Black
666.0,Vivillon,80,52,50,90,50,89,411,Bug,Flying,Shield Dust,Compound Eyes,Friend Guard,Black
731.0,Pikipek,35,75,30,30,30,65,265,Normal,Flying,Keen Eye,Skill Link,Pickup,Black
732.0,Trumbeak,55,85,50,40,50,75,355,Normal,Flying,Keen Eye,Skill Link,Pickup,Black
733.0,Toucannon,80,120,75,75,75,60,485,Normal,Flying,Keen Eye,Skill Link,Sheer Force,Black
757.0,Salandit,48,44,40,71,40,77,320,Poison,Fire,Corrosion,Oblivious,Oblivious,Black
758.0,Salazzle,68,64,60,111,60,117,480,Poison,Fire,Corrosion,Oblivious,Oblivious,Black
771.0,Pyukumuku,55,60,130,30,130,5,410,Water,,Innards Out,Unaware,Unaware,Black
796.0,Xurkitree,83,89,71,173,71,83,570,Electric,,Beast Boost,,,Black
799.0,Guzzlord,223,101,53,97,53,43,570,Dark,Dragon,Beast Boost,,,Black
800.0,Necrozma,97,107,101,127,89,79,600,Psychic,,Prism Armor,,,Black

### Compound boolean queries
You can use boolean operations (OR, AND, NOT) to combine conditions
- The vertical line | represents OR 
- The ampersand & represents AND 
- The tilde ~ or exclamation-equal != represents NOT

We will look for pokemon with specific types to demonstrate compound queries

### OR queries
In the following example, we query for all pokemon who have at least part "Dragon" typing.

The vertical line | represents the element-wise "OR" operation. "OR" operations require either or both statements on either side of the operation to be true.

Thus, the below query 

```query = (pokedex_df['Type I']=='Dragon') | (pokedex_df['Type II']=='Dragon')```

asks, for each row, if 'Type I' is equal to "Dragon" OR 'Type II' is equal to "Dragon"

In [18]:
query = (pokedex_df['Type I']=='Dragon') | (pokedex_df['Type II']=='Dragon')
pokedex_df.loc[query] # Get all of the entries corresponding to the above query

,Pokemon,HP,Atk,Def,SpAtk,SpDef,Speed,Total,Type I,Type II,Ability I,Ability II,Hidden Ability,Color
Index,,,,,,,,,,,,,,
178.0,Dratini,41,64,45,50,50,50,300,Dragon,,Shed Skin,,Marvel Scale,Blue
179.0,Dragonair,61,84,65,70,70,70,420,Dragon,,Shed Skin,,Marvel Scale,Blue
180.0,Dragonite,91,134,95,100,100,80,600,Dragon,Flying,Inner Focus,,Multiscale,Brown
134.0,Kingdra,75,95,95,95,95,85,540,Water,Dragon,Swift Swim,Sniper,Damp,Blue
356.0,Vibrava,50,70,50,50,50,70,340,Ground,Dragon,Levitate,,,Green
357.0,Flygon,80,100,80,80,80,100,520,Ground,Dragon,Levitate,,,Green
361.0,Altaria,75,70,90,70,105,80,490,Dragon,Flying,Natural Cure,,Cloud Nine,Blue
400.0,Bagon,45,75,60,40,30,50,300,Dragon,,Rock Head,,Sheer Force,Blue
401.0,Shelgon,65,95,100,60,50,50,420,Dragon,,Rock Head,,Overcoat,White
402.0,Salamence,95,135,80,110,80,100,600,Dragon,Flying,Intimidate,,Moxie,Blue
409.0,Latias,80,80,90,110,130,110,600,Dragon,Psychic,Levitate,,,Red
410.0,Latios,80,90,80,130,110,110,600,Dragon,Psychic,Levitate,,,Blue
413.0,Rayquaza,105,150,90,150,90,95,680,Dragon,Flying,Air Lock,,,Green
463.0,Gible,58,70,45,40,45,42,300,Dragon,Ground,Sand Veil,,Rough Skin,Blue
464.0,Gabite,68,90,65,50,55,82,410,Dragon,Ground,Sand Veil,,Rough Skin,Blue
465.0,Garchomp,108,130,95,80,85,102,600,Dragon,Ground,Sand Veil,,Rough Skin,Blue
483.0,Dialga,100,120,120,150,100,90,680,Steel,Dragon,Pressure,,Telepathy,White
484.0,Palkia,90,120,100,150,120,100,680,Water,Dragon,Pressure,,Telepathy,Purple
487.0,Giratina,150,100,120,100,120,90,680,Ghost,Dragon,Pressure,,Telepathy,Black
487.1,Giratina (O),150,120,100,120,100,90,680,Ghost,Dragon,Levitate,,,Black
610.0,Axew,46,87,60,30,40,57,320,Dragon,,Rivalry,Mold Breaker,Unnerve,Green
611.0,Fraxure,66,117,70,40,50,67,410,Dragon,,Rivalry,Mold Breaker,Unnerve,Green
612.0,Haxorus,76,147,90,60,70,97,540,Dragon,,Rivalry,Mold Breaker,Unnerve,Yellow
621.0,Druddigon,77,120,90,60,90,48,485,Dragon,,Rough Skin,Sheer Force,Mold Breaker,Red
633.0,Deino,52,65,50,45,50,38,300,Dark,Dragon,Hustle,,,Blue
634.0,Zweilous,72,85,70,65,70,58,420,Dark,Dragon,Hustle,,,Blue
635.0,Hydreigon,92,105,90,125,90,98,600,Dark,Dragon,Levitate,,,Blue
643.0,Reshiram,100,120,100,150,120,90,680,Dragon,Fire,Turboblaze,,,White
644.0,Zekrom,100,150,120,120,100,90,680,Dragon,Electric,Teravolt,,,Black
646.0,Kyurem,125,130,90,130,90,95,660,Dragon,Ice,Pressure,,,Gray
691.0,Dragalge,65,75,90,97,123,44,494,Poison,Dragon,Poison Point,Poison Touch,Adaptability,Brown
696.0,Tyrunt,58,89,77,45,45,48,362,Rock,Dragon,Strong Jaw,,Sturdy,Brown
697.0,Tyrantrum,82,121,119,69,59,71,521,Rock,Dragon,Strong Jaw,,Sturdy,Red
704.0,Goomy,45,50,35,55,75,40,300,Dragon,,Sap Sipper,Hydration,Gooey,Purple
705.0,Sliggoo,68,75,53,83,113,60,452,Dragon,,Sap Sipper,Hydration,Gooey,Purple
706.0,Goodra,90,100,70,110,150,80,600,Dragon,,Sap Sipper,Hydration,Gooey,Purple
714.0,Noibat,40,30,35,45,40,55,245,Flying,Dragon,Frisk,Infiltrator,Telepathy,Purple
715.0,Noivern,85,70,80,97,80,123,535,Flying,Dragon,Frisk,Infiltrator,Telepathy,Purple
718.0,Zygarde,108,100,121,81,95,95,600,Dragon,Ground,Aura Break,,,Green
776.0,Turtonator,60,78,135,91,85,36,485,Fire,Dragon,Shell Armor,,,Red
780.0,Drampa,78,60,85,135,91,36,485,Normal,Dragon,Berserk,Sap Sipper,Cloud Nine,White
782.0,Jangmo-o,45,55,65,45,45,45,300,Dragon,,Bulletproof,Soundproof,Overcoat,Gray
783.0,Hakamo-o,55,75,90,65,70,65,420,Dragon,Fighting,Bulletproof,Soundproof,Overcoat,Gray
784.0,Kommo-o,75,110,125,100,105,85,600,Dragon,Fighting,Bulletproof,Soundproof,Overcoat,Gray
799.0,Guzzlord,223,101,53,97,53,43,570,Dark,Dragon,Beast Boost,,,Black

In [19]:
(pokedex_df['Type I']=='Dragon').all()

False

### AND queries
The ampersand `&` character represents the element-wise boolean operation "AND". In order for an "AND" statement to be true, both conditions on either side of the operation must be true.

We can combine boolean operations to construct complex queries: for example, getting all pokemon who are both Dragon and Flying types. The query below looks for pokemon who are EITHER (Primary Type "Flying" AND Secondary Type "Dragon") OR (Primary Type "Dragon" AND Secondary Type "Flying")

Note that parentheses should be used to group operations so that the order of operations is clear

In [20]:
# you can use the backslash operator \ to continue code on the next line
query = ((pokedex_df['Type I']=='Flying') & (pokedex_df['Type II']=='Dragon'))\
        | ((pokedex_df['Type I']=='Dragon') & (pokedex_df['Type II']=='Flying'))
pokedex_df.loc[query]

,Pokemon,HP,Atk,Def,SpAtk,SpDef,Speed,Total,Type I,Type II,Ability I,Ability II,Hidden Ability,Color
Index,,,,,,,,,,,,,,
180.0,Dragonite,91,134,95,100,100,80,600,Dragon,Flying,Inner Focus,,Multiscale,Brown
361.0,Altaria,75,70,90,70,105,80,490,Dragon,Flying,Natural Cure,,Cloud Nine,Blue
402.0,Salamence,95,135,80,110,80,100,600,Dragon,Flying,Intimidate,,Moxie,Blue
413.0,Rayquaza,105,150,90,150,90,95,680,Dragon,Flying,Air Lock,,,Green
714.0,Noibat,40,30,35,45,40,55,245,Flying,Dragon,Frisk,Infiltrator,Telepathy,Purple
715.0,Noivern,85,70,80,97,80,123,535,Flying,Dragon,Frisk,Infiltrator,Telepathy,Purple

### NOT queries
There are two ways to do negation. Consider the following query for selecting all pokemon who are Fire type, but not Flying

```
query = ((pokedex_df['Type I']=='Fire') & ~(pokedex_df['Type II']=='Flying'))\
        | ((pokedex_df['Type I']!='Flying') & (pokedex_df['Type II']=='Fire'))
```

The first way to do negation is with the tilde ~ symbol, which negates the subsequent boolean statement:
We use this in `~(pokedex_df['Type II']=='Flying')`.
The parentheses determine order of operations. First we find all entries where their secondary type is "Flying"
Then the tilde in front negates that statement, flipping all True values to False, and vice versa

The second way to do negation is using the != notation, which represents "not equal to"
We use this in `(pokedex_df['Type I']!='Flying')`
This finds all entries where their primary type is not equal to "Flying"

In [21]:
query = ((pokedex_df['Type I']=='Fire') & ~(pokedex_df['Type II']=='Flying'))\
        | ((pokedex_df['Type I']!='Flying') & (pokedex_df['Type II']=='Fire'))

pokedex_df.loc[query]

,Pokemon,HP,Atk,Def,SpAtk,SpDef,Speed,Total,Type I,Type II,Ability I,Ability II,Hidden Ability,Color
Index,,,,,,,,,,,,,,
4.0,Charmander,39,52,43,60,50,65,309,Fire,,Blaze,,Solar Power,Red
5.0,Charmeleon,58,64,58,80,65,80,405,Fire,,Blaze,,Solar Power,Red
39.0,Vulpix,38,41,40,50,65,65,299,Fire,,Flash Fire,,Drought,Brown
40.0,Ninetales,73,76,75,81,100,100,505,Fire,,Flash Fire,,Drought,Yellow
63.0,Growlithe,55,70,45,70,50,60,350,Fire,,Intimidate,Flash Fire,Justified,Brown
64.0,Arcanine,90,110,80,100,80,95,555,Fire,,Intimidate,Flash Fire,Justified,Brown
83.0,Ponyta,50,85,55,65,65,90,410,Fire,,Run Away,Flash Fire,Flame Body,Yellow
84.0,Rapidash,65,100,70,80,80,105,500,Fire,,Run Away,Flash Fire,Flame Body,Yellow
149.0,Magmar,65,95,57,100,85,93,495,Fire,,Flame Body,,Vital Spirit,Red
160.0,Flareon,65,130,60,95,110,65,525,Fire,,Flash Fire,,Guts,Red
186.0,Cyndaquil,39,52,43,60,50,65,309,Fire,,Blaze,,Flash Fire,Yellow
187.0,Quilava,58,64,58,80,65,80,405,Fire,,Blaze,,Flash Fire,Yellow
188.0,Typhlosion,78,84,78,109,85,100,534,Fire,,Blaze,,Flash Fire,Yellow
248.0,Slugma,40,40,40,70,40,20,250,Fire,,Magma Armor,Flame Body,Weak Armor,Red
249.0,Magcargo,50,50,120,80,80,30,410,Fire,Rock,Magma Armor,Flame Body,Weak Armor,Red
260.0,Houndour,45,60,30,80,50,65,330,Dark,Fire,Early Bird,Flash Fire,Unnerve,Black
261.0,Houndoom,75,90,50,110,80,95,500,Dark,Fire,Early Bird,Flash Fire,Unnerve,Black
148.0,Magby,45,75,37,70,55,83,365,Fire,,Flame Body,,Vital Spirit,Red
268.0,Entei,115,115,85,90,75,100,580,Fire,,Pressure,,Flash Fire,Brown
279.0,Torchic,45,60,40,70,50,45,310,Fire,,Blaze,,Speed Boost,Red
280.0,Combusken,60,85,60,85,60,55,405,Fire,Fighting,Blaze,,Speed Boost,Red
281.0,Blaziken,80,120,70,110,70,80,530,Fire,Fighting,Blaze,,Speed Boost,Red
349.0,Numel,60,60,40,65,45,35,305,Fire,Ground,Oblivious,Simple,Own Tempo,Yellow
350.0,Camerupt,70,100,70,105,75,40,460,Fire,Ground,Magma Armor,Solid Rock,Anger Point,Red
351.0,Torkoal,70,85,140,85,70,20,470,Fire,,White Smoke,,Shell Armor,Brown
419.0,Chimchar,44,58,44,58,44,61,309,Fire,,Blaze,,Iron Fist,Brown
420.0,Monferno,64,78,52,78,52,81,405,Fire,Fighting,Blaze,,Iron Fist,Brown
421.0,Infernape,76,104,71,104,71,108,534,Fire,Fighting,Blaze,,Iron Fist,Brown
150.0,Magmortar,75,95,67,125,95,83,540,Fire,,Flame Body,,Vital Spirit,Red
479.1,Rotom (Heat),50,65,107,105,107,86,520,Electric,Fire,Levitate,,,Red
485.0,Heatran,91,90,106,130,106,77,600,Fire,Steel,Flash Fire,,Flame Body,Brown
494.0,Victini,100,100,100,100,100,100,600,Psychic,Fire,Victory Star,,,Yellow
498.0,Tepig,65,63,45,45,45,45,308,Fire,,Blaze,,Thick Fat,Red
499.0,Pignite,90,93,55,70,55,55,418,Fire,Fighting,Blaze,,Thick Fat,Red
500.0,Emboar,110,123,65,100,65,65,528,Fire,Fighting,Blaze,,Reckless,Red
513.0,Pansear,50,53,48,53,48,64,316,Fire,,Gluttony,,Blaze,Red
514.0,Simisear,75,98,63,98,63,101,498,Fire,,Gluttony,,Blaze,Red
554.0,Darumaka,70,90,45,15,45,50,315,Fire,,Hustle,,Inner Focus,Red
555.0,Darmanitan,105,140,55,30,55,95,480,Fire,,Sheer Force,,Zen Mode,Red
555.1,Darmanitan (Z),105,30,105,140,105,55,540,Fire,Psychic,,,Zen Mode,Red
607.0,Litwick,50,30,55,65,55,20,275,Ghost,Fire,Flash Fire,Flame Body,Shadow Tag,White
608.0,Lampent,60,40,60,95,60,55,370,Ghost,Fire,Flash Fire,Flame Body,Shadow Tag,Black
609.0,Chandelure,60,55,90,145,90,80,520,Ghost,Fire,Flash Fire,Flame Body,Shadow Tag,Black
631.0,Heatmor,85,97,66,105,66,65,484,Fire,,Gluttony,Flash Fire,White Smoke,Red
636.0,Larvesta,55,85,55,50,55,60,360,Bug,Fire,Flame Body,,Swarm,White
637.0,Volcarona,85,60,65,135,105,100,550,Bug,Fire,Flame Body,,Swarm,White
643.0,Reshiram,100,120,100,150,120,90,680,Dragon,Fire,Turboblaze,,,White
653.0,Fennekin,40,45,40,62,60,60,307,Fire,,Blaze,,Magician,Red
654.0,Braixen,59,59,58,90,70,73,409,Fire,,Blaze,,Magician,Red
655.0,Delphox,75,69,72,114,100,104,534,Fire,Psychic,Blaze,,Magician,Red
667.0,Litleo,62,50,58,73,54,72,369,Fire,Normal,Rivalry,Unnerve,Moxie,Brown
668.0,Pyroar,86,68,72,109,66,106,507,Fire,Normal,Rivalry,Unnerve,Moxie,Brown
721.0,Volcanion,80,110,120,130,90,70,600,Fire,Water,Water Absorb,,,Brown
725.0,Litten,45,65,40,60,40,70,320,Fire,,Blaze,Intimidate,,Red
726.0,Torracat,65,85,50,80,50,90,420,Fire,,Blaze,Intimidate,,Red
727.0,Incineroar,95,115,90,80,90,60,530,Fire,Dark,Blaze,Intimidate,,Red
757.0,Salandit,48,44,40,71,40,77,320,Poison,Fire,Corrosion,Oblivious,Oblivious,Black
758.0,Salazzle,68,64,60,111,60,117,480,Poison,Fire,Corrosion,Oblivious,Oblivious,Black
776.0,Turtonator,60,78,135,91,85,36,485,Fire,Dragon,Shell Armor,,,Red

## Sorting
Dataframes can be sorted by value

In [22]:
pokedex_df.sort_values('Pokemon', ascending=False) # Sort by name descending

,Pokemon,HP,Atk,Def,SpAtk,SpDef,Speed,Total,Type I,Type II,Ability I,Ability II,Hidden Ability,Color
Index,,,,,,,,,,,,,,
718.0,Zygarde,108,100,121,81,95,95,600,Dragon,Ground,Aura Break,,,Green
634.0,Zweilous,72,85,70,65,70,58,420,Dark,Dragon,Hustle,,,Blue
44.0,Zubat,40,45,35,30,40,55,245,Poison,Flying,Inner Focus,,Infiltrator,Purple
570.0,Zorua,40,65,40,80,40,65,330,Dark,,Illusion,,,Gray
571.0,Zoroark,60,105,60,120,60,105,510,Dark,,Illusion,,,Gray
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
681.0,Aegislash,60,50,150,50,150,60,520,Steel,Ghost,Stance Change,,,Brown
617.0,Accelgor,80,70,40,100,60,145,495,Bug,,Hydration,Sticky Hold,Unburden,Red
388.0,Absol,65,130,60,75,60,75,465,Dark,,Pressure,Super Luck,Justified,White
69.0,Abra,25,20,15,105,55,90,310,Psychic,,Synchronize,Inner Focus,Magic Guard,Brown
478.0,Abomasnow,90,92,75,92,85,60,494,Ice,Grass,Snow Warning,,Soundproof,White

In [23]:
# You can sort by multiple columns, by ascending or descending methods
pokedex_df.sort_values(['Type I','Type II', 'Total'], ascending=False) # Sort by type combination, then stats descending

,Pokemon,HP,Atk,Def,SpAtk,SpDef,Speed,Total,Type I,Type II,Ability I,Ability II,Hidden Ability,Color
Index,,,,,,,,,,,,,,
424.0,Empoleon,84,86,88,111,101,60,530,Water,Steel,Torrent,,Defiant,Blue
565.0,Carracosta,74,108,133,83,65,32,495,Water,Rock,Solid Rock,Sturdy,Swift Swim,Blue
398.0,Relicanth,100,90,130,45,65,55,485,Water,Rock,Swift Swim,Rock Head,Sturdy,Gray
253.0,Corsola,55,55,85,65,85,35,380,Water,Rock,Hustle,Natural Cure,Regenerator,Pink
564.0,Tirtouga,54,78,103,53,45,22,355,Water,Rock,Solid Rock,Sturdy,Swift Swim,Blue
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
292.0,Cascoon,50,35,55,25,25,15,205,Bug,,Shed Skin,,,Purple
664.0,Scatterbug,38,35,40,27,25,35,200,Bug,,Shield Dust,Compound Eyes,Friend Guard,Black
10.0,Caterpie,45,30,35,20,20,45,195,Bug,,Shield Dust,,Run Away,Green
289.0,Wurmple,45,45,35,20,30,20,195,Bug,,Shield Dust,,Run Away,Red
430.0,Kricketot,37,25,41,25,41,25,194,Bug,,Shed Skin,,Run Away,Red

## Adding columns, rows, and changing values
You can add another column like:
```
dataframe['NewColumnName'] = value
```
`value` can be a single value, an array of the same size as the index of `dataframe`, a pandas `Series`, or a dictionary mapping `index: value` for entries in the dataframe index

In [24]:
pokedex_df['Nickname'] = None
pokedex_df

,Pokemon,HP,Atk,Def,SpAtk,SpDef,Speed,Total,Type I,Type II,Ability I,Ability II,Hidden Ability,Color,Nickname
Index,,,,,,,,,,,,,,,
1.0,Bulbasaur,45,49,49,65,65,45,318,Grass,Poison,Overgrow,,Chlorophyll,Green,None
2.0,Ivysaur,60,62,63,80,80,60,405,Grass,Poison,Overgrow,,Chlorophyll,Green,None
3.0,Venusaur,80,82,83,100,100,80,525,Grass,Poison,Overgrow,,Chlorophyll,Green,None
4.0,Charmander,39,52,43,60,50,65,309,Fire,,Blaze,,Solar Power,Red,None
5.0,Charmeleon,58,64,58,80,65,80,405,Fire,,Blaze,,Solar Power,Red,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
798.0,Kartana,59,181,131,59,31,109,570,Grass,Steel,Beast Boost,,,White,None
799.0,Guzzlord,223,101,53,97,53,43,570,Dark,Dragon,Beast Boost,,,Black,None
800.0,Necrozma,97,107,101,127,89,79,600,Psychic,,Prism Armor,,,Black,None
801.0,Magearna,80,95,115,130,115,65,600,Steel,Fairy,Soul-Heart,,,Gray,None
802.0,Marshadow,90,125,80,90,90,125,600,Fighting,Ghost,Technician,,,Gray,None

In [25]:
# you can change the value of an entry using indexing and assignment =
pokedex_df.loc[4,'Nickname'] = 'Abby' # indexing using .loc[] pokedex entry 4, 'Nickname column'
pokedex_df.iloc[113,-1] = 'Terry' # indexing using .iloc[] 113rd row, last column
pokedex_df.iloc[[3,113],:]

,Pokemon,HP,Atk,Def,SpAtk,SpDef,Speed,Total,Type I,Type II,Ability I,Ability II,Hidden Ability,Color,Nickname
Index,,,,,,,,,,,,,,,
4.0,Charmander,39,52,43,60,50,65,309,Fire,,Blaze,,Solar Power,Red,Abby
129.0,Tangela,65,55,115,100,40,60,435,Grass,,Chlorophyll,Leaf Guard,Regenerator,Blue,Terry

## Combining Dataframes

Dataframes can be combined with or without shared values. Dataframes can be combined in different ways:
- append (without shared values)
- merge 
- join (inner, left, right, outer) 

It is important to clean NA values for proper combiinations, this can be done with:
- '.combine_first()'

### Appending

Some of you may have noticed that the pokedex file only includes Generations 1-7 of pokemon. Let's add the pokemon from Gen 8. The file `pokedex_gen8.csv` contains the pokedex entries for all of the pokemon that show up in the 8th generation of games (Sword/Shield).

In [26]:
# you can add another dataframe on to the end using append()
gen8_pokedex_df = pd.read_csv('pokedex_gen8.csv') # create a dataframe with new entries

In [27]:
appended_pokedex_df = pd.concat([pokedex_df, gen8_pokedex_df], ignore_index=True, sort=False) # the sort=False keyword prevents the columns from being reordered alphabetically
appended_pokedex_df = appended_pokedex_df.fillna('').drop_duplicates() # some cleanup operations, replace NaN with emptry strings, and drop duplicate rows
appended_pokedex_df

,Pokemon,HP,Atk,Def,SpAtk,SpDef,Speed,Total,Type I,Type II,Ability I,Ability II,Hidden Ability,Color,Nickname,Galar Pokedex Number,Weight_kg,Height_m,Weight_lbs,Height_ft,Cap_Rate,Egg_Steps,Classification
0,Bulbasaur,45,49,49,65,65,45,318.0,Grass,Poison,Overgrow,,Chlorophyll,Green,,,,,,,,,
1,Ivysaur,60,62,63,80,80,60,405.0,Grass,Poison,Overgrow,,Chlorophyll,Green,,,,,,,,,
2,Venusaur,80,82,83,100,100,80,525.0,Grass,Poison,Overgrow,,Chlorophyll,Green,,,,,,,,,
3,Charmander,39,52,43,60,50,65,309.0,Fire,,Blaze,,Solar Power,Red,Abby,,,,,,,,
4,Charmeleon,58,64,58,80,65,80,405.0,Fire,,Blaze,,Solar Power,Red,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1215,Drakloak,68,80,50,60,50,102,,dragon,ghost,Clear Body,Infiltrator,Cursed Body,,,396.0,11.0,1.4,24.3,4.583,45.0,10240.0,Caretaker Pokémon
1216,Dragapult,88,120,75,100,75,142,,dragon,ghost,Clear Body,Infiltrator,Cursed Body,,,397.0,50.0,3.0,110.2,9.833,45.0,10240.0,Stealth Pokémon
1217,Zacian,92,130,115,80,115,138,,fairy,,Intrepid Sword,,,,,398.0,110.0,2.8,242.5,9.167,10.0,30720.0,Warrior Pokémon
1218,Zamazenta,92,130,115,80,115,138,,fighting,,Dauntless Shield,,,,,399.0,210.0,2.9,463.0,9.5,10.0,30720.0,Warrior Pokémon
1219,Eternatus,140,85,95,145,95,130,,poison,dragon,Pressure,,,,,400.0,950.0,20.0,2094.4,65.583,255.0,30720.0,Gigantic Pokémon

However, you may notice that some pokemon show up twice in the combined dataframe, and since the entries in `gen8_pokedex_df` includes different columns, `remove_duplicates` does not see those entries as duplicates.

To remedy this, we can index both dataframes by the name of the pokemon and use the [`combine_first`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.combine_first.html#pandas.DataFrame.combine_first) function to fill in the null values of one dataframe with the corresponding values in the other.

In [28]:
gen8_pokedex_indexed_by_name = gen8_pokedex_df.reset_index().set_index('Pokemon')
combined_pokedex_df = pokedex_indexed_by_name.combine_first(gen8_pokedex_indexed_by_name)
combined_pokedex_df

,Ability I,Ability II,Atk,Cap_Rate,Classification,Color,Def,Egg_Steps,Galar Pokedex Number,HP,Height_ft,Height_m,Hidden Ability,Index,SpAtk,SpDef,Speed,Total,Type I,Type II,Weight_kg,Weight_lbs,index
Pokemon,,,,,,,,,,,,,,,,,,,,,,,
Abomasnow,Snow Warning,,92,60.0,Frosted Tree Pokémon,White,75,5120.0,97.0,90,7.250,2.2,Soundproof,478.0,92,85,60,494.0,Ice,Grass,135.5,298.7,96.0
Abra,Synchronize,Inner Focus,20,NaN,NaN,Brown,15,NaN,NaN,25,NaN,NaN,Magic Guard,69.0,105,55,90,310.0,Psychic,,NaN,NaN,NaN
Absol,Pressure,Super Luck,130,NaN,NaN,White,60,NaN,NaN,65,NaN,NaN,Justified,388.0,75,60,75,465.0,Dark,,NaN,NaN,NaN
Accelgor,Hydration,Sticky Hold,70,75.0,Shell Out Pokémon,Red,40,3840.0,276.0,80,2.583,0.8,Unburden,617.0,100,60,145,495.0,Bug,,25.3,55.8,275.0
Aegislash,Stance Change,,50,45.0,Royal Sword Pokémon,Brown,150,5120.0,332.0,60,5.583,1.7,,681.0,50,150,60,520.0,Steel,Ghost,53.0,116.8,331.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Zoroark,Illusion,,105,NaN,NaN,Gray,60,NaN,NaN,60,NaN,NaN,,571.0,120,60,105,510.0,Dark,,NaN,NaN,NaN
Zorua,Illusion,,65,NaN,NaN,Gray,40,NaN,NaN,40,NaN,NaN,,570.0,80,40,65,330.0,Dark,,NaN,NaN,NaN
Zubat,Inner Focus,,45,NaN,NaN,Purple,35,NaN,NaN,40,NaN,NaN,Infiltrator,44.0,30,40,55,245.0,Poison,Flying,NaN,NaN,NaN
Zweilous,Hustle,,85,45.0,Hostile Pokémon,Blue,70,10240.0,387.0,72,4.583,1.4,,634.0,65,70,58,420.0,Dark,Dragon,50.0,110.2,386.0
Zygarde,Aura Break,,100,NaN,NaN,Green,121,NaN,NaN,108,NaN,NaN,,718.0,81,95,95,600.0,Dragon,Ground,NaN,NaN,NaN

### Merges and Joins
A more advanced way to join dataframes is using the `merge` or `join` operations.

For those who have worked with SQL-style databases before, you may be familiar with `merge` and `join` operations. They are done to combine two tables or dataframes which share values in certain columns. This allows us to look up entries in another dataframe using the values of our current dataframe.

In this example, we will use `merge` to get the stats for a team of pokemon. This dataframe will just contain the names and nicknames of the pokemon that we want on our team. After we perform a merge, we will get a dataframe with the respective statistics for the pokemon we've chosen.

In [35]:
# feel free to replace the names of pokemon with ones you want on your team
team_df = pd.DataFrame({'my pokemon':['Bulbasaur','Squirtle','Charmander'],
                       'nickname':['leafygurl','h2woah','toaster']})
team_df

print(combined_pokedex_df[combined_pokedex_df["Pokemon"] == "Arceus"])

KeyError: 'Pokemon'

There are four merge/join types in `pandas`:
- (INNER) JOIN: Returns records that have matching values in both tables
- (LEFT) JOIN: Returns all records from the left table, and the matched records from the right table 
- (RIGHT) JOIN: Returns all records from the right table, and the matched records from the left table   
- (OUTER) JOIN: Returns all records when there is a match in either left or right table
    

 ![inner join illustration, venn diagram with intersection colored in, from w3schools sql lesson](https://www.w3schools.com/sql/img_innerjoin.gif)
  ![left join illustration, venn diagram with full left circle colored in, from w3schools sql lesson](https://www.w3schools.com/sql/img_leftjoin.gif)
  ![right join illustration, venn diagram with full right circle colored in, from w3schools sql lesson](https://www.w3schools.com/sql/img_rightjoin.gif)
  ![outer join illustration, venn diagram with union of two circles colored in, from w3schools sql lesson](https://www.w3schools.com/sql/img_fulljoin.gif)

The information that we need in order to perform a merge is:
- what dataframes to merge
- what kind of merge/join (inner/left/right/outer)
- what columns to merge on in each dataframe

Knowing this, let's look at the function signature of merge for a dataframe

In [ ]:
# you can use the question mark symbol ? to examine the function signature
pokedex_df.merge?

The answers to the following questions to get the team dataframe with stats are:

**what dataframes to merge?**
`team_df` and `combined_pokedex_df`
    
**what kind of merge/join (inner/left/right/outer)?**
inner or left 
    
**what columns to merge on in each dataframe**
for `team_df`, the column is `my pokemon`, for `combined_pokedex_df`, it is the index.

In [ ]:
team_with_stats = team_df.merge(combined_pokedex_df, how='inner',
                               left_on='my pokemon', right_index=True)
team_with_stats

In [ ]:
# we can select specific columns from the dataframe
team_with_stats.loc[:,['my pokemon','nickname','Total']]

### Exercise
Put together a team of pokemon by editing `team_df` and performing a `merge`. Remember that you can only have 6 pokemon on a team at once.

## Calculations and operations
There are various ways to do math to the dataframes

### Column operations
You can perform basic math element-wise between columns, such as addition, subtraction, multiplication, and division.
- Column operations: basic arthmitic, compute ratios, etcs. 
- Universal operations: can be done on entire numerical dataset: 
 - '.apply()' : apply an arbitrary function to each row or column. 
 - If you pass the name of a function (e.g. np.mean or the name of any function you've written), you can apply it to either each column, or each row using '.apply()'.
 - Descriptive statistics have built-in functions (mean, median, mode, standard deviation, count, quantile),
- '.groupby()' : grouping column values in a dataframe and applying operations to them. 

Note that the `gen8_pokedex_df` does not contain a `Total` stats column, so currently the gen8 pokemon have `NaN` in that column. We can fix that, because `Total` is generated as the sum of the respective `HP` `Atk` `Def` `SpAtk` `SpDef` and `Speed`. We can add the entire columns at once, without having to loop over each entry. Pandas supports vectorized operations behind the scenes.

In [ ]:
# these are the entries missing 'Total' stats
combined_pokedex_df.loc[combined_pokedex_df['Total'].isnull()]

In [ ]:
combined_pokedex_df['Total'] = combined_pokedex_df['HP']\
                               + combined_pokedex_df['Atk']\
                               + combined_pokedex_df['Def']\
                               + combined_pokedex_df['SpAtk']\
                               + combined_pokedex_df['SpDef']\
                               + combined_pokedex_df['Speed']

In [ ]:
pokedex_df['Total']/ pokedex_df['HP'] # computes the ratio between total stats and HP

### Universal functions
Universal functions can operate on entire dataframes or slices of dataframes. They return a dataframe copy with the same index as the original dataframe. Numpy universal functions can be applied to any numeric dataframe or slice.

In [ ]:
np.log(pokedex_df.loc[:,'HP':'Total'].astype(float)) # take natural log of all stats
# again, these functions operate on each element independently, and return a dataframe with the same index and size of input

### .apply()
You can apply an arbitrary function to each row or column using the `.apply()` function.

If you pass the name of a function (e.g. np.mean, or the name of any function you've written), you can apply it to either each column, or each row using `.apply()`

In [ ]:
pokedex_df.loc[:,'Atk':'Speed'].apply(np.mean) # applies the function np.mean() to each column

In [ ]:
pokedex_df.loc[:,'Atk':'Speed'].apply(np.mean, axis=1) # if you wanted to apply it to each row instead, use the argument axis=1

The above example is actually a bit unnecessary. There are several built-in functions in dataframes, including a `.mean()` which has the same functionality.

In [ ]:
pokedex_df.loc[:,'Atk':'Speed'].mean()

In [ ]:
pokedex_df.loc[:,'Atk':'Speed'].mean(axis=1) #applies per row

Most [descriptive statistics](https://pandas.pydata.org/pandas-docs/stable/reference/frame.html#computations-descriptive-stats) (median, mode, standard deviation, count, quantile, etc) have built-in functions. Where `.apply()` really shines, however, is for applying custom functions. 

To show that functionality, let's take a sidebar and talk about lambda functions.

#### Lambda functions
Sometimes you want to define a function, but you don't want to write the whole function declaration setup 
```
def functionname(inputs):
  ...
  return outputs
```

In those situations, you can write lambda (also known as anonymous) functions. The syntax for a lambda function is:

```
functionname = lambda x: operations_on_x
```

For example, if you wanted to write a function that squares the input, you could write:

In [ ]:
square_it = lambda x: x**2 # recall that ** is exponentiation in python, this function returns the square of the input
for num in range(10):
  print(square_it(num))

This is especially useful if some function takes another function as an argument, like panda's `.apply()`

The typical usage of `.apply()` is:

`dataframe_obj.apply(functionname)`, which calls `functionname` on each column of `dataframe_obj`

However, you can replace `functionname` with a lambda function. In this example, we use the following lambda function:

```lambda col: [np.min(col), np.max(col)]```

The word `col` represents the argument, and then to the right of the colon, we return a list with two elements: the minimum and maximum values of the column

In [ ]:
stats_ranges = pokedex_df.loc[:,'HP':'Total'].apply(lambda col: [np.min(col), np.max(col)])
print(stats_ranges)

the above can be expanded into a dataframe:

In [ ]:
pokedex_df.loc[:,'HP':'Total'].apply(lambda col: [np.min(col), np.mean(col), np.max(col)], result_type='expand')
# each respective row corresponds to the function applied to the column

In [ ]:
# we can rename the rows to make it more interpretable. Also note the backslash \
# character allows a command to continue onto the next line, ignoring whitespace
pokedex_df.loc[:,'HP':'Total']\
          .apply(lambda col: [np.min(col), np.mean(col), np.max(col)], result_type='expand')\
          .rename({0:'min', 1:'mean', 2:'max'})

### Groupby
Dataframes can be grouped by column values, and operations can be applied to each group

In [ ]:
# counts the number of pokemon of each type combination
pokedex_df.groupby(['Type I','Type II'])['Total'].count()

In [ ]:
# gets the range of stats for each type combination
pokedex_df.groupby(['Type I','Type II'])['Total'].apply(lambda col: [np.min(col), np.max(col)])

# Multi-level indexing
In this section, we'll cover some more advanced topics in pandas, including 
*   Multi-indexing
*   Pivot tables

We'll be introducing some more data to play with, based on state populations over time

In [ ]:
state_populations_url = 'https://raw.githubusercontent.com/jakevdp/data-USstates/master/state-population.csv'
state_abbrevs_url = 'https://raw.githubusercontent.com/jakevdp/data-USstates/master/state-abbrevs.csv'
state_areas_url = 'https://raw.githubusercontent.com/jakevdp/data-USstates/master/state-areas.csv'

state_areas = pd.read_csv(state_areas_url, index_col='state')
state_areas.head() # just print top 5 rows

In [ ]:
state_abbrevs = pd.read_csv(state_abbrevs_url)
state_abbrevs.head()

In [ ]:
state_populations = pd.read_csv(state_populations_url) 
state_populations.head(10) #print first 10 rows

In [ ]:
state_populations.tail()

Note that the state populations are just listed by abbreviations. It may be useful to include the state names as a column in a table. We have this information in the `state_abbrevs` table. We'd like to merge it with the population data.

The function `pd.merge()` merges two dataframes using set logic.

In [ ]:
merged = pd.merge(state_populations, state_abbrevs, how='outer',
                 left_on='state/region', right_on='abbreviation')
# The arguments left_on and right_on specify what columns to join on. It looks for matching values in each dataframe
# and fills in the additional columns of the merged dataframe based on the matching data
# The 'how' argument specifies what kind of join. Outer means keep all entries even if one does not show up in the other
# conversely, 'inner' discards rows where a corresponding entry does not exist in the other
merged

In [ ]:
# we can also drop the unnecessary extra abbreviation column now
merged = merged.drop('abbreviation', axis=1) #drop from columns
merged.head()

In [ ]:
# we can check if there were any missing values
merged.isnull().any()

In [ ]:
# let's see where the issue is. What entries are missing population entries?
merged.loc[merged['population'].isnull()]

In [ ]:
# what about where there's no state entry?
merged.loc[merged['state'].isnull(), 'state/region']

In [ ]:
# more concicely, we can use .unique() to only see the unique values
merged.loc[merged['state'].isnull(), 'state/region'].unique()

In [ ]:
# We can fix this easily
merged.loc[merged['state/region'] == 'PR', 'state'] = 'Puerto Rico'
merged.loc[merged['state/region'] == 'USA', 'state'] = 'United States'
merged.isnull().any()

In [ ]:
# now let's combine the data with the area data
final = pd.merge(merged, state_areas, on='state', how='left')
final.head()

In [ ]:
# we can use the .query() syntax to search for specific data
data2010 = final.query("year == 2010 & ages == 'total'") # specify column name 
data2010.set_index('state', inplace=True) # equivalent to data2010 = data2010.set_index('state')
data2010.head()

In [ ]:
# Let's compute the density of each state and then sort by density
density = data2010['population'] / data2010['area (sq. mi)']
density.sort_values(ascending=False, inplace=True)
density

In [ ]:
density.tail()

### Exercises
Compute the total population of the entire united states, as well as its population density for each year.

Sort the states by population density.

What year saw the biggest change in population for the US as a whole?

Which states had the biggest percentage change in population in that year?

## Multiindexing
You can use multiple columns to define an index, as long as each row has a unique combination of values within those columns. In the following example, we will use the columns "state/region", "year", and "ages" of the population dataframe as an index

We use the `.set_index(['column_name1', 'column_name2, ...])'` command to create a multiindex from existing columns.

Note that many operations require a multiindex to be sorted, so we also call `.sort_index()` on the dataframe. Also, `.set_index()` and `.sort_index()` return a _copy_ of the dataframe, so we assign the output to itself to update the value.

In [ ]:
# set index to use multiple columns
final = final.set_index(['state/region','year','ages']) # overwrite old version with new version with index set
final = final.sort_index() # replace itself with a version with a sorted index
final.tail(10) #print last 10 entries

In [ ]:
final.loc[('MA',2009,'total'):('WY',2011,'total')]

### Stacking and unstacking
Columns can also have multiple levels. In fact, the columns can be thought of as just another index that runs horizontally. This is most easily illustrated by stacking, unstacking, and transposing.

You can convert a level of the row index to a column level using the `.unstack()` command. Conversely, `.stack()` moves a column level to the index

In [ ]:
unstacked = final.unstack(level='ages') # you can unstack by level name; this moves the 'ages' categories into the column index
unstacked

In [ ]:
restacked = unstacked.stack('ages', dropna=False) # stacks the column level back into the row index
# by default, .stack() omits entries with NaN. If you want to preserve the NaN entries, use the option dropna=False
restacked == final # just like the original state_populations dataframe

In [ ]:
final.unstack(level=0) # you can also unstack using integer levels. Here we unstacked level 0, corresponding to state/region

You can switch the row and column index using the transpose function `.T`

In [ ]:
final.unstack(level=0).T

### Pivoting
Pivoting is another advanced way to transform data. It creates a new dataframe using the values of columns as `index` and `column` values. 

You can then aggregate using `aggfunc` the elements of another column, which becomes the `values` of this new dataframe.

In [ ]:
# let's create a table which lists all pokemon for given type combinations
pokedex_df.pivot_table(values='Pokemon', # line breaks within parentheses automatically continue onto next line
                       index='Type I', # values of Type I become index entries
                       columns='Type II', # likewise Type II become columns
                       aggfunc=lambda x:", ".join(x)).fillna('') # the lambda function here just joins a list of strings using a comma
                      # we also fill nan values with empty string for aesthetics

In [ ]:
# compute the average stats for each type combination
pokedex_df.unstack()
pokedex_df.pivot_table(values='Total',
                       index='Type I', 
                       columns='Type II', 
                       aggfunc=lambda x: np.mean(x)).fillna('')

In [ ]:
# You can compute multiple aggregations on multiple columns by passing a dict
# into the aggfunc argument: aggfunc={'column_name':[list_of_function_names]}
# Note that in this case, the 'value' argument is ignored
pokedex_df.pivot_table(index='Type I', 
                       columns='Type II', 
                       aggfunc={'Total':[lambda x: np.mean(x),lambda x: np.std(x)], 
                                'Atk':[lambda x: np.mean(x),lambda x: np.std(x)]}).fillna('')

# Exercise
Using this data (or any other data you're interested in and you find online), put together an analysis using pandas that investigates an interesting question.

It can be serious or silly. Like "Do states with higher population density tend to vote democratic?" (you'd need to pull additional data for this) or "Do pokemon whose names start with the letter D have better stats than those who start with F?"

We'll ask some volunteers to present their analysis at the end